Repository Chloekkk/cub3D, pull requests merged in 2022-09, with the labels that each got.

#3 Feature/validate character
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  Makefile
  include/parse.h
  src/parse/validate_map.c
Labels: feature

#5 Feature/parse info
  .vscode/launch.json
  .vscode/settings.json
  Makefile
  img/EA.xpm
  img/NO.xpm
  img/SO.xpm
  img/WE.xpm
  include/cub3D.h
  include/parse.h
  include/test.h
  include/util.h
  map/b.cub
  map/c.cub
  src/__test__/map.c
  src/main/main.c
  src/parse/parse.c
  src/parse/parse_graphic_info.c
  src/parse/parse_map_info.c
  src/parse/valid_extension.c
  src/util/ft_make_img.c
  src/util/ft_str_to_rgb.c
  src/util/ft_trim_line.c
Labels: feature

#6 Feature/str to rgb
  src/util/ft_str_to_rgb.c
Labels: feature

#7 Feature/validate wall
  Makefile
  include/cub3D.h
  include/parse.h
  include/util.h
  src/parse/check_around_space.c
  src/parse/valid_edge_wall.c
  src/parse/valid_extension.c
  src/parse/valid_inner_wall.c
  src/parse/valid_map.c
  src/parse/validate_map.c
  src/util/ft_make_img.c
  src/util/ft_strtrim_back.c
Labels: feature

#10 Feature/map parsing
  Makefile
  include/cub3D.h
  include/parse.h
  include/util.h
  src/parse/check_around_space.c
  src/parse/parse_map_info.c
  src/parse/valid_inner_wall.c
  src/parse/valid_map.c
  src/util/ft_trim_line.c
Labels: feature, refactor

#12 [Feature] Refactor cub3d structure
  Makefile
  img/space.xpm
  img/wall.xpm
  include/cub3D.h
  include/draw.h
  include/graphic.h
  include/handler.h
  include/minimap.h
  include/util.h
  src/draw/draw.c
  src/draw/draw_line.c
  src/draw/draw_minimap.c
  src/handler/keypress_handler.c
  src/main/main.c
  src/minimap/minimap.c
  src/parse/parse.c
  src/util/ft_make_img.c
  src/util/ft_put_img.c
Labels: feature, refactor

#13 [Refactor] Add t_state of vector state structure
  include/cub3D.h
Labels: refactor

#15 Hotfix/player position
  Makefile
  include/cub3D.h
  include/parse.h
  src/main/main.c
  src/parse/parse.c
  src/parse/parse_state.c
  src/parse/valid_map.c
Labels: bug, refactor

#18 Refactor ray casting
  Makefile
  img/space.png
  img/space.xpm
  img/wall.png
  img/wall.xpm
  include/cub3D.h
  include/draw.h
  include/init.h
  include/raycast.h
  map/c.cub
  map/d.cub
  map/overflow.cub
  src/draw/draw_line.c
  src/draw/draw_minimap.c
  src/handler/keypress_handler.c
  src/init/init.c
  src/init/init_info.c
  src/init/init_state.c
  src/main/main.c
  src/minimap/minimap.c
  src/parse/parse_graphic_info.c
  src/parse/parse_state.c
  src/raycast/init_ray.c
  src/raycast/ray_dda.c
  src/raycast/raycast.c
  src/util/ft_str_to_rgb.c
Labels: refactor

#22 Hotfix/graphic parsing
  src/parse/parse_graphic_info.c
Labels: bug

#24 [Feature] texture rendering
  Makefile
  img/EA.xpm
  img/NO.xpm
  img/SO.xpm
  img/WE.xpm
  img/space.png
  img/space.xpm
  img/wall.png
  img/wall.xpm
  include/cub3D.h
  include/draw.h
  include/init.h
  include/raycast.h
  src/draw/draw_game.c
  src/draw/draw_pixel.c
  src/game/create_bg_img.c
  src/game/start_game.c
  src/init/init.c
  src/init/init_info.c
  src/parse/parse_graphic_info.c
Labels: feature, refactor

#25 [Refactor] refactoring header files
  include/cub3D.h
  include/parse.h
  include/raycast.h
  include/test.h
Labels: refactor

#26 [Hotfix] Decorate makefile
  Makefile
  lib/mlx/Makefile
  src/__test__/map.c
  src/parse/parse_graphic_info.c
  src/parse/parse_map_info.c
  src/parse/parse_state.c
  src/util/ft_get_valid_rgb.c
  src/util/ft_strtrim_back.c
Labels: feature

#27 Feature/norminette
  Makefile
  include/cub3D.h
  include/draw.h
  include/error.h
  include/game.h
  include/handler.h
  include/init.h
  include/parse.h
  include/raycast.h
  include/test.h
  include/util.h
  src/draw/draw_game.c
  src/draw/draw_line.c
  src/draw/draw_minimap.c
  src/draw/draw_pixel.c
  src/draw/draw_ray.c
  src/draw/draw_square.c
  src/draw/draw_wall.c
  src/error/throw_error.c
  src/game/close_game.c
  src/game/start_game.c
  src/handler/check_wall_collision.c
  src/handler/keypress_handler.c
  src/init/init.c
  src/init/init_info.c
  src/init/init_state.c
  src/main/main.c
  src/parse/parse.c
  src/parse/parse_graphic_info.c
  src/parse/parse_map_info.c
  src/parse/parse_state.c
  src/parse/valid_edge_wall.c
  src/parse/valid_extension.c
  src/parse/valid_inner_wall.c
  src/parse/valid_map.c
  src/raycast/raycast.c
  src/raycast/set_ray.c
  src/raycast/update_ray.c
  src/util/ft_get_line.c
  src/util/ft_get_valid_rgb.c
  src/util/ft_make_img.c
  src/util/ft_str_to_rgb.c
  src/util/ft_strtrim_back.c
  src/util/ft_trim_line.c
Labels: refactor

#28 [Fix] Fix incompatible make error in move_pos function
  src/handler/keypress_handler.c
Labels: bug

#29 [Norm] Complete norminette
  src/game/start_game.c
  src/handler/keypress_handler.c
Labels: refactor

#30 [Fix] Fix img_path error
  include/util.h
  src/util/ft_make_img.c
Labels: bug

#31 [Hotfix] double id error
  include/parse.h
  src/parse/parse_graphic_info.c
  src/parse/parse_map_info.c
  src/parse/valid_edge_wall.c
  src/parse/valid_inner_wall.c
  src/parse/valid_map.c
Labels: bug

#33 Hotfix/map parsing error
  src/parse/parse.c
  src/parse/parse_state.c
  src/parse/valid_map.c
Labels: bug
